<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heading_CATEGORIES</name>
   <tag></tag>
   <elementGuidId>34253021-c149-45ac-bec3-fbe8f729ceb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72230a0f-4a9e-412f-9172-2a061d606651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>d28cb6a8-b0ac-4e6f-9433-6f231bd230d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cat</value>
      <webElementGuid>9409c47f-7c08-46d6-a3fc-62b41410a0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CATEGORIES</value>
      <webElementGuid>a4397cb7-2e8c-4ae3-a00a-462e58493347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cat&quot;)</value>
      <webElementGuid>eb6e8e14-4563-4a37-8526-48d8dc98f647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cat']</value>
      <webElementGuid>52209176-eecb-4367-88be-c1288f91f1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contcont']/div/div/div/a</value>
      <webElementGuid>54b61abc-bb5d-4357-8b29-945707eb3b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CATEGORIES')]</value>
      <webElementGuid>d06acf60-a204-41dc-9776-6bd36fbe98b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[12]</value>
      <webElementGuid>62eeb9d4-cbc8-49b3-ad92-d705143e0922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>699e4b6f-e297-4b3a-beb5-33f03cf1d72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cat' and (text() = 'CATEGORIES' or . = 'CATEGORIES')]</value>
      <webElementGuid>12037b99-eac3-42b3-8f24-197ed7129e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
